"""
Download every Nobilia front swatch in fronts_catalog.json, crop a clean
handle/logo/seam-free patch into references/, and (re)build materials.json with a
colour sampled from each crop plus finish/roughness heuristics.

Run (needs network - run from the PowerShell tool, not the sandboxed shell):
  python fetch_and_crop.py            # all fronts
  python fetch_and_crop.py 412 334    # only these numbers

Then generate textures with:  python generate_fronts.py
"""
import json
import ssl
import sys
import urllib.request
from pathlib import Path

from PIL import Image

# This machine's Python CA store rejects nobilia's cert chain (works in PowerShell).
# Public catalog images, so fall back to an unverified context.
_SSL_CTX = ssl.create_default_context()
_SSL_CTX.check_hostname = False
_SSL_CTX.verify_mode = ssl.CERT_NONE


def _fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    return urllib.request.urlopen(req, timeout=30, context=_SSL_CTX).read()

ROOT = Path(__file__).parent
REF_DIR = ROOT / "references"
RAW_DIR = ROOT / "work" / "raw_fronts"
CATALOG = json.loads((ROOT / "fronts_catalog.json").read_text(encoding="utf-8"))


def finish_and_roughness(line, name):
    s = f"{line} {name}".lower()
    if any(k in s for k in ("high gloss", "ultra high gloss", "flash", "focus", "pura", "novalux")):
        return "high_gloss_lacquer", 0.15
    if any(k in s for k in ("supermatt", "ultra matt", "ultramatt", "perfect matt", "easytouch", "touch")):
        return "supermatt_lacquer", 0.85
    if any(k in s for k in ("oak", "walnut", "wood")):
        return "woodgrain", 0.65
    if any(k in s for k in ("concrete", "slate", "stone", "structured", "look", "riva", "stoneart")):
        return "stone_concrete", 0.70
    if "steel" in s or "inox" in s:
        return "brushed_metal", 0.35
    if "honed" in s or "senso" in s:
        return "honed_lacquer", 0.55
    return "matte_lacquer", 0.78


def sample_hex(img):
    small = img.resize((32, 32))
    px = list(small.getdata()) if hasattr(small, "getdata") else []
    n = len(px)
    r = sum(p[0] for p in px) // n
    g = sum(p[1] for p in px) // n
    b = sum(p[2] for p in px) // n
    return f"#{r:02x}{g:02x}{b:02x}"


def slug(name):
    return name.replace(" ", "_").replace(",", "").replace("/", "-")


def main():
    REF_DIR.mkdir(parents=True, exist_ok=True)
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    base = CATALOG["image_base"]
    box = CATALOG["crop_box"]
    only = set(sys.argv[1:])
    fronts = [f for f in CATALOG["fronts"] if not only or f["number"] in only]

    materials = []
    for f in fronts:
        num, name, line = f["number"], f["name"], f["line"]
        stem = f"{num}_{slug(name)}"
        url = f"{base}/front_{line}_{num}_d.jpg"
        raw = RAW_DIR / f"{line}_{num}.jpg"
        ref = REF_DIR / f"{stem}.jpg"
        try:
            if not raw.exists():
                raw.write_bytes(_fetch(url))
            im = Image.open(raw).convert("RGB")
            W, H = im.size
            crop = im.crop((int(box[0] * W), int(box[1] * H), int(box[2] * W), int(box[3] * H)))
            crop.save(ref, quality=95)
            finish, rough = finish_and_roughness(line, name)
            materials.append({
                "number": num, "name": name, "line": line.upper(),
                "ref": f"references/{stem}.jpg", "hex": sample_hex(crop),
                "finish": finish, "roughness_base": rough,
            })
            print(f"  OK  {num} {name}  hex={materials[-1]['hex']}  {finish}")
        except Exception as e:
            print(f"  FAIL {num} {name}: {e}")

    out = {"_comment": "Auto-generated by fetch_and_crop.py. Edit hex/finish/roughness "
                        "by hand if a swatch needs tuning, then run generate_fronts.py.",
           "materials": materials}
    (ROOT / "materials.json").write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"\nWrote {len(materials)} entries to materials.json and crops to references/")


if __name__ == "__main__":
    main()
