using System.IO;
using System.Text;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

namespace RoomRevive.IntentSelector.EditorTools
{
    /// <summary>
    /// Dumps the current state of the IntentSelector prefab(s) and data assets
    /// into a markdown snapshot. Future AI sessions (or humans) read this BEFORE
    /// making changes, so manual overrides are preserved.
    ///
    /// This tool only READS. It never mutates anything.
    /// </summary>
    public static class IntentSelectorSnapshotExporter
    {
        const string BaseFolder = "Assets/RoomRevive/UI/IntentSelector";
        const string SnapshotFolder = BaseFolder + "/Snapshots";
        const string MainPrefabPath = BaseFolder + "/Prefabs/IntentSelectorUI.prefab";
        const string CatalogPath = BaseFolder + "/Data/IntentStateCatalog.asset";
        const string ThemePath = BaseFolder + "/Data/IntentSelectorTheme.asset";

        [MenuItem("Tools/RoomRevive/Intent Selector/Export Snapshot")]
        public static string ExportSnapshot()
        {
            EnsureFolder(SnapshotFolder);

            string path = SnapshotFolder + "/IntentSelectorUI.md";
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("# IntentSelector — Current State Snapshot");
            sb.AppendLine();
            sb.AppendLine($"_Generated: {System.DateTime.Now:yyyy-MM-dd HH:mm}_");
            sb.AppendLine();
            sb.AppendLine("This file is regenerated by `Tools/RoomRevive/Intent Selector/Export Snapshot`.");
            sb.AppendLine("AI agents and humans should read it before editing the prefab or scripts.");
            sb.AppendLine("See `docs/AI_EDIT_PROTOCOL.md` for the workflow.");
            sb.AppendLine();

            WriteCatalogSection(sb);
            WriteThemeSection(sb);
            WriteMainPrefabSection(sb);
            WriteCardPrefabsSection(sb);

            File.WriteAllText(path, sb.ToString());
            AssetDatabase.ImportAsset(path);

            Debug.Log($"[IntentSelectorSnapshotExporter] Wrote snapshot: {path}");
            EditorGUIUtility.PingObject(AssetDatabase.LoadAssetAtPath<Object>(path));

            return path;
        }

        // ── Section writers ─────────────────────────────────────────────────

        static void WriteCatalogSection(StringBuilder sb)
        {
            sb.AppendLine("## Catalog");
            sb.AppendLine();

            IntentStateCatalog catalog = AssetDatabase.LoadAssetAtPath<IntentStateCatalog>(CatalogPath);
            if (catalog == null)
            {
                sb.AppendLine($"`{CatalogPath}` — **missing**.");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"`{CatalogPath}` — {catalog.Count} state(s).");
            sb.AppendLine();
            sb.AppendLine("| # | id | displayName | hasIcon | hasImage | hasAtmosphereMusic | hasCardPrefab | flags |");
            sb.AppendLine("|---|----|-------------|---------|----------|--------------------|---------------|-------|");

            for (int i = 0; i < catalog.Count; i++)
            {
                IntentStateData s = catalog.GetState(i);
                if (s == null) { sb.AppendLine($"| {i} | _null_ |  |  |  |  |  |  |"); continue; }

                string flags = (s.showProductUI ? "P" : "-") + (s.showCabinetUI ? "C" : "-")
                             + (s.showFridges ? "F" : "-") + (s.showCabinets ? "K" : "-");

                sb.AppendLine($"| {i} | `{s.id}` | {s.displayName} | {YesNo(s.icon)} | {YesNo(s.cardImage)} | {YesNo(s.atmosphereMusic)} | {YesNo(s.cardPrefab)} | {flags} |");
            }

            sb.AppendLine();
            sb.AppendLine("_Flags column: P=showProductUI, C=showCabinetUI, F=showFridges, K=showCabinets_");
            sb.AppendLine();
        }

        static void WriteThemeSection(StringBuilder sb)
        {
            sb.AppendLine("## Theme");
            sb.AppendLine();

            IntentSelectorTheme theme = AssetDatabase.LoadAssetAtPath<IntentSelectorTheme>(ThemePath);
            if (theme == null)
            {
                sb.AppendLine($"`{ThemePath}` — **missing**.");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"`{ThemePath}`");
            sb.AppendLine();
            sb.AppendLine($"- normalScale = {theme.normalScale}");
            sb.AppendLine($"- hoverScale = {theme.hoverScale}");
            sb.AppendLine($"- selectedScale = {theme.selectedScale}");
            sb.AppendLine($"- scaleLerpSpeed = {theme.scaleLerpSpeed}");
            sb.AppendLine($"- greyedOutOverlayAlpha = {theme.greyedOutOverlayAlpha}");
            sb.AppendLine($"- greyedOutHoveredAlpha = {theme.greyedOutHoveredAlpha}");
            sb.AppendLine($"- greyedOutPressedAlpha = {theme.greyedOutPressedAlpha}");
            sb.AppendLine($"- hoverOverlayAlpha = {theme.hoverOverlayAlpha}");
            sb.AppendLine($"- pressedOverlayAlpha = {theme.pressedOverlayAlpha}");
            sb.AppendLine($"- overlayLerpSpeed = {theme.overlayLerpSpeed}");
            sb.AppendLine();
        }

        static void WriteMainPrefabSection(StringBuilder sb)
        {
            sb.AppendLine("## Main Prefab — `IntentSelectorUI.prefab`");
            sb.AppendLine();

            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(MainPrefabPath);
            if (prefab == null)
            {
                sb.AppendLine($"`{MainPrefabPath}` — **missing**. Run `Tools/RoomRevive/Intent Selector/Create Default Assets And Prefab`.");
                sb.AppendLine();
                return;
            }

            sb.AppendLine($"`{MainPrefabPath}`");
            sb.AppendLine();
            sb.AppendLine("### Components on root");
            sb.AppendLine();
            WriteComponentList(sb, prefab);

            IntentSelectorController controller = prefab.GetComponent<IntentSelectorController>();
            if (controller != null)
            {
                sb.AppendLine("### IntentSelectorController");
                sb.AppendLine();
                sb.AppendLine($"- catalog → `{AssetPathOrNull(controller.catalog)}`");
                sb.AppendLine($"- theme → `{AssetPathOrNull(controller.theme)}`");
                sb.AppendLine($"- view → {(controller.view != null ? "(on same GameObject)" : "**null**")}");
                sb.AppendLine($"- selectStateOnStart = {controller.selectStateOnStart}");
                sb.AppendLine($"- startFromCatalogDefault = {controller.startFromCatalogDefault}");
                sb.AppendLine($"- keyboardDebug = {controller.keyboardDebug}");
                sb.AppendLine();
            }

            IntentSelectorView view = prefab.GetComponent<IntentSelectorView>();
            if (view != null)
            {
                sb.AppendLine("### IntentSelectorView");
                sb.AppendLine();
                sb.AppendLine($"- cardsContainer → `{(view.cardsContainer != null ? view.cardsContainer.name : "null")}`");
                sb.AppendLine($"- cardTemplate → `{(view.cardTemplate != null ? view.cardTemplate.name : "null")}`");
                sb.AppendLine($"- instantiateCardsFromCatalog = {view.instantiateCardsFromCatalog}");
                sb.AppendLine($"- hideTemplateAtRuntime = {view.hideTemplateAtRuntime}");
                sb.AppendLine($"- cardViews.Count = {(view.cardViews != null ? view.cardViews.Count : 0)}");
                sb.AppendLine();
            }

            sb.AppendLine("### Hierarchy");
            sb.AppendLine();
            sb.AppendLine("```");
            WriteHierarchy(sb, prefab.transform, 0);
            sb.AppendLine("```");
            sb.AppendLine();
        }

        static void WriteCardPrefabsSection(StringBuilder sb)
        {
            sb.AppendLine("## Card Prefabs");
            sb.AppendLine();

            string[] guids = AssetDatabase.FindAssets("t:Prefab Card_", new[] { BaseFolder + "/Prefabs/Cards" });
            if (guids == null || guids.Length == 0)
            {
                sb.AppendLine("_No card prefabs found under `Prefabs/Cards/`._");
                sb.AppendLine();
                return;
            }

            System.Array.Sort(guids);
            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                GameObject cardPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (cardPrefab == null) continue;

                sb.AppendLine($"### `{path}`");
                sb.AppendLine();

                IntentCardView card = cardPrefab.GetComponent<IntentCardView>();
                if (card != null)
                {
                    sb.AppendLine($"- title.text = `{TextOrNull(card.titleText)}`");
                    sb.AppendLine($"- title.font = `{FontName(card.titleText)}` @ {FontSize(card.titleText)}");
                    sb.AppendLine($"- subtitle.text = `{TextOrNull(card.subtitleText)}`");
                    sb.AppendLine($"- subtitle.font = `{FontName(card.subtitleText)}` @ {FontSize(card.subtitleText)}");
                    sb.AppendLine($"- imageArea.sprite = `{SpriteName(card.imageArea)}`");
                    sb.AppendLine($"- iconImage.sprite = `{SpriteName(card.iconImage)}`");
                    sb.AppendLine($"- stateOverlay = `{(card.stateOverlay != null ? "wired" : "null")}`");
                    sb.AppendLine();
                }

                sb.AppendLine("```");
                WriteHierarchy(sb, cardPrefab.transform, 0);
                sb.AppendLine("```");
                sb.AppendLine();
            }
        }

        // ── Helpers ─────────────────────────────────────────────────────────

        static void WriteComponentList(StringBuilder sb, GameObject go)
        {
            Component[] components = go.GetComponents<Component>();
            for (int i = 0; i < components.Length; i++)
            {
                Component c = components[i];
                sb.AppendLine($"- `{(c != null ? c.GetType().Name : "<missing script>")}`");
            }
            sb.AppendLine();
        }

        static void WriteHierarchy(StringBuilder sb, Transform t, int depth)
        {
            string indent = new string(' ', depth * 2);
            string activeMarker = t.gameObject.activeSelf ? "" : " [inactive]";
            sb.AppendLine($"{indent}{t.name}{activeMarker}");

            for (int i = 0; i < t.childCount; i++)
                WriteHierarchy(sb, t.GetChild(i), depth + 1);
        }

        static string AssetPathOrNull(Object o) => o == null ? "null" : AssetDatabase.GetAssetPath(o);
        static string YesNo(Object o) => o != null ? "✓" : "—";
        static string TextOrNull(TMP_Text t) => t == null ? "null" : (t.text ?? "");
        static string FontName(TMP_Text t) => t == null || t.font == null ? "default" : t.font.name;
        static string FontSize(TMP_Text t) => t == null ? "?" : t.fontSize.ToString();
        static string SpriteName(Image img) => img == null || img.sprite == null ? "none" : img.sprite.name;

        static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            string parent = Path.GetDirectoryName(path).Replace('\\', '/');
            string leaf = Path.GetFileName(path);
            if (!AssetDatabase.IsValidFolder(parent)) return;
            AssetDatabase.CreateFolder(parent, leaf);
        }
    }
}
